<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.data</groupId>
        <artifactId>profile-platform</artifactId>
        <version>1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>profile-connector-plugins</artifactId>
    <packaging>pom</packaging>

    <name>profile-connector-plugins</name>
    <url>http://maven.apache.org</url>
    <modules>
        <module>profile-connector-clickhouse</module>
        <module>profile-connector-jdbc</module>
        <module>profile-connector-all</module>
        <module>profile-connector-mysql</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
