import type { ApiResponse, DataSource, DataSourceSchema } from '@/types'

// Mock Schema 数据
export const mockSchemas: DataSourceSchema[] = [
  {
    schemaId: 'mysql',
    schemaName: 'MySQL',
    schemaType: 1,
    sourceType: 1,
    jdbcProtocol: 'jdbc:mysql',
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '', required: 1, encrypt: 2, tip: '请输入主机地址' },
      { showName: '端口', key: 'port', value: '3306', required: 1, encrypt: 2, tip: '请输入端口' },
      { showName: '数据库名', key: 'database', value: '', required: 1, encrypt: 2, tip: '请输入数据库名' },
      { showName: '用户名', key: 'username', value: '', required: 1, encrypt: 2, tip: '请输入用户名' },
      { showName: '密码', key: 'password', value: '', required: 1, encrypt: 1, tip: '请输入密码' },
    ],
  },
  {
    schemaId: 'clickhouse',
    schemaName: 'ClickHouse',
    schemaType: 2,
    sourceType: 1,
    jdbcProtocol: 'jdbc:clickhouse',
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '', required: 1, encrypt: 2, tip: '请输入主机地址' },
      { showName: '端口', key: 'port', value: '8123', required: 1, encrypt: 2, tip: '请输入端口' },
      { showName: '数据库名', key: 'database', value: '', required: 1, encrypt: 2, tip: '请输入数据库名' },
      { showName: '用户名', key: 'username', value: 'default', required: 1, encrypt: 2, tip: '请输入用户名' },
      { showName: '密码', key: 'password', value: '', required: 2, encrypt: 1, tip: '请输入密码' },
    ],
  },
  {
    schemaId: 'postgresql',
    schemaName: 'PostgreSQL',
    schemaType: 3,
    sourceType: 1,
    jdbcProtocol: 'jdbc:postgresql',
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '', required: 1, encrypt: 2, tip: '请输入主机地址' },
      { showName: '端口', key: 'port', value: '5432', required: 1, encrypt: 2, tip: '请输入端口' },
      { showName: '数据库名', key: 'database', value: '', required: 1, encrypt: 2, tip: '请输入数据库名' },
      { showName: '用户名', key: 'username', value: '', required: 1, encrypt: 2, tip: '请输入用户名' },
      { showName: '密码', key: 'password', value: '', required: 1, encrypt: 1, tip: '请输入密码' },
    ],
  },
  {
    schemaId: 'hologres',
    schemaName: 'Hologres',
    schemaType: 4,
    sourceType: 1,
    jdbcProtocol: 'jdbc:postgresql',
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '', required: 1, encrypt: 2, tip: '请输入主机地址' },
      { showName: '端口', key: 'port', value: '80', required: 1, encrypt: 2, tip: '请输入端口' },
      { showName: '数据库名', key: 'database', value: '', required: 1, encrypt: 2, tip: '请输入数据库名' },
      { showName: '用户名', key: 'username', value: '', required: 1, encrypt: 2, tip: '请输入用户名' },
      { showName: '密码', key: 'password', value: '', required: 1, encrypt: 1, tip: '请输入密码' },
    ],
  },
  {
    schemaId: 'maxcompute',
    schemaName: 'MaxCompute',
    schemaType: 5,
    sourceType: 1,
    jdbcProtocol: 'jdbc:odps',
    configTemplate: [
      { showName: 'Endpoint', key: 'endpoint', value: '', required: 1, encrypt: 2, tip: '请输入Endpoint' },
      { showName: '项目名称', key: 'project', value: '', required: 1, encrypt: 2, tip: '请输入项目名称' },
      { showName: 'Access ID', key: 'accessId', value: '', required: 1, encrypt: 2, tip: '请输入Access ID' },
      { showName: 'Access Key', key: 'accessKey', value: '', required: 1, encrypt: 1, tip: '请输入Access Key' },
    ],
  },
  {
    schemaId: 'hbase',
    schemaName: 'HBase',
    schemaType: 6,
    sourceType: 1,
    jdbcProtocol: '',
    configTemplate: [
      { showName: 'ZK地址', key: 'zkQuorum', value: '', required: 1, encrypt: 2, tip: '请输入ZooKeeper地址' },
      { showName: 'ZK端口', key: 'zkPort', value: '2181', required: 1, encrypt: 2, tip: '请输入ZooKeeper端口' },
    ],
  },
  {
    schemaId: 'hive',
    schemaName: 'Hive',
    schemaType: 7,
    sourceType: 1,
    jdbcProtocol: 'jdbc:hive2',
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '', required: 1, encrypt: 2, tip: '请输入主机地址' },
      { showName: '端口', key: 'port', value: '10000', required: 1, encrypt: 2, tip: '请输入端口' },
      { showName: '数据库名', key: 'database', value: 'default', required: 1, encrypt: 2, tip: '请输入数据库名' },
      { showName: '用户名', key: 'username', value: '', required: 2, encrypt: 2, tip: '请输入用户名' },
      { showName: '密码', key: 'password', value: '', required: 2, encrypt: 1, tip: '请输入密码' },
    ],
  },
  {
    schemaId: 'elasticsearch',
    schemaName: 'Elasticsearch',
    schemaType: 8,
    sourceType: 1,
    jdbcProtocol: '',
    configTemplate: [
      { showName: '集群地址', key: 'hosts', value: '', required: 1, encrypt: 2, tip: '请输入集群地址，多个用逗号分隔' },
      { showName: '用户名', key: 'username', value: '', required: 2, encrypt: 2, tip: '请输入用户名' },
      { showName: '密码', key: 'password', value: '', required: 2, encrypt: 1, tip: '请输入密码' },
    ],
  },
  {
    schemaId: 'redis',
    schemaName: 'Redis',
    schemaType: 9,
    sourceType: 1,
    jdbcProtocol: '',
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '', required: 1, encrypt: 2, tip: '请输入主机地址' },
      { showName: '端口', key: 'port', value: '6379', required: 1, encrypt: 2, tip: '请输入端口' },
      { showName: '密码', key: 'password', value: '', required: 2, encrypt: 1, tip: '请输入密码' },
      { showName: '数据库', key: 'database', value: '0', required: 2, encrypt: 2, tip: '请输入数据库索引' },
    ],
  },
  {
    schemaId: 'kafka',
    schemaName: 'Kafka',
    schemaType: 10,
    sourceType: 1,
    jdbcProtocol: '',
    configTemplate: [
      { showName: 'Bootstrap Servers', key: 'bootstrapServers', value: '', required: 1, encrypt: 2, tip: '请输入Bootstrap Servers' },
    ],
  },
  {
    schemaId: 'mongodb',
    schemaName: 'MongoDB',
    schemaType: 11,
    sourceType: 1,
    jdbcProtocol: '',
    configTemplate: [
      { showName: '连接字符串', key: 'uri', value: '', required: 1, encrypt: 2, tip: '请输入MongoDB连接字符串' },
    ],
  },
  {
    schemaId: 'doris',
    schemaName: 'Doris',
    schemaType: 12,
    sourceType: 1,
    jdbcProtocol: 'jdbc:mysql',
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '', required: 1, encrypt: 2, tip: '请输入主机地址' },
      { showName: '端口', key: 'port', value: '9030', required: 1, encrypt: 2, tip: '请输入端口' },
      { showName: '数据库名', key: 'database', value: '', required: 1, encrypt: 2, tip: '请输入数据库名' },
      { showName: '用户名', key: 'username', value: '', required: 1, encrypt: 2, tip: '请输入用户名' },
      { showName: '密码', key: 'password', value: '', required: 1, encrypt: 1, tip: '请输入密码' },
    ],
  },
]

// Mock 数据源数据
export const mockDataSources: DataSource[] = [
  {
    datasourceId: 'ds_001',
    datasourceName: 'production_mysql',
    datasourceDesc: '生产环境MySQL数据库',
    schemaId: 'mysql',
    schemaName: 'MySQL',
    schemaType: 1,
    creator: 'admin',
    modifier: 'admin',
    gmtCreate: '2024-01-15 10:30:00',
    gmtModified: '2024-03-20 14:22:00',
    config: JSON.stringify({
      host: '192.168.1.100',
      port: '3306',
      database: 'user_db',
      username: 'app_user',
    }),
    configTemplate: [
      { showName: '主机地址', key: 'host', value: '192.168.1.100', required: 1, encrypt: 2, tip: '' },
      { showName: '端口', key: 'port', value: '3306', required: 1, encrypt: 2, tip: '' },
      { showName: '数据库名', key: 'database', value: 'user_db', required: 1, encrypt: 2, tip: '' },
      { showName: '用户名', key: 'username', value: 'app_user', required: 1, encrypt: 2, tip: '' },
      { showName: '密码', key: 'password', value: '******', required: 1, encrypt: 1, tip: '' },
    ],
  },
  {
    datasourceId: 'ds_002',
    datasourceName: 'analytics_clickhouse',
    datasourceDesc: '分析型ClickHouse集群',
    schemaId: 'clickhouse',
    schemaName: 'ClickHouse',
    schemaType: 2,
    creator: 'admin',
    modifier: 'zhangsan',
    gmtCreate: '2024-02-01 09:00:00',
    gmtModified: '2024-03-15 16:45:00',
    config: JSON.stringify({
      host: 'clickhouse.internal.com',
      port: '8123',
      database: 'analytics',
      username: 'analytics',
    }),
    configTemplate: [
      { showName: '主机地址', key: 'host', value: 'clickhouse.internal.com', required: 1, encrypt: 2, tip: '' },
      { showName: '端口', key: 'port', value: '8123', required: 1, encrypt: 2, tip: '' },
      { showName: '数据库名', key: 'database', value: 'analytics', required: 1, encrypt: 2, tip: '' },
      { showName: '用户名', key: 'username', value: 'analytics', required: 1, encrypt: 2, tip: '' },
      { showName: '密码', key: 'password', value: '******', required: 2, encrypt: 1, tip: '' },
    ],
  },
  {
    datasourceId: 'ds_003',
    datasourceName: 'dw_hologres',
    datasourceDesc: '数据仓库Hologres',
    schemaId: 'hologres',
    schemaName: 'Hologres',
    schemaType: 4,
    creator: 'admin',
    modifier: 'admin',
    gmtCreate: '2024-02-20 11:20:00',
    gmtModified: '2024-02-20 11:20:00',
    config: JSON.stringify({
      host: 'hologres.cn-beijing.aliyuncs.com',
      port: '80',
      database: 'dw_db',
      username: 'holo_user',
    }),
    configTemplate: [
      { showName: '主机地址', key: 'host', value: 'hologres.cn-beijing.aliyuncs.com', required: 1, encrypt: 2, tip: '' },
      { showName: '端口', key: 'port', value: '80', required: 1, encrypt: 2, tip: '' },
      { showName: '数据库名', key: 'database', value: 'dw_db', required: 1, encrypt: 2, tip: '' },
      { showName: '用户名', key: 'username', value: 'holo_user', required: 1, encrypt: 2, tip: '' },
      { showName: '密码', key: 'password', value: '******', required: 1, encrypt: 1, tip: '' },
    ],
  },
  {
    datasourceId: 'ds_004',
    datasourceName: 'bi_postgresql',
    datasourceDesc: 'BI系统PostgreSQL',
    schemaId: 'postgresql',
    schemaName: 'PostgreSQL',
    schemaType: 3,
    creator: 'lisi',
    modifier: 'lisi',
    gmtCreate: '2024-03-01 08:30:00',
    gmtModified: '2024-03-10 10:15:00',
    config: JSON.stringify({
      host: 'pg.bi.internal',
      port: '5432',
      database: 'bi_reports',
      username: 'bi_reader',
    }),
    configTemplate: [
      { showName: '主机地址', key: 'host', value: 'pg.bi.internal', required: 1, encrypt: 2, tip: '' },
      { showName: '端口', key: 'port', value: '5432', required: 1, encrypt: 2, tip: '' },
      { showName: '数据库名', key: 'database', value: 'bi_reports', required: 1, encrypt: 2, tip: '' },
      { showName: '用户名', key: 'username', value: 'bi_reader', required: 1, encrypt: 2, tip: '' },
      { showName: '密码', key: 'password', value: '******', required: 1, encrypt: 1, tip: '' },
    ],
  },
  {
    datasourceId: 'ds_005',
    datasourceName: 'odps_maxcompute',
    datasourceDesc: '阿里云MaxCompute',
    schemaId: 'maxcompute',
    schemaName: 'MaxCompute',
    schemaType: 5,
    creator: 'admin',
    modifier: 'admin',
    gmtCreate: '2024-03-05 14:00:00',
    gmtModified: '2024-03-05 14:00:00',
    config: JSON.stringify({
      endpoint: 'http://service.cn.maxcompute.aliyun.com/api',
      project: 'my_project',
      accessId: 'LTAI******',
    }),
    configTemplate: [
      { showName: 'Endpoint', key: 'endpoint', value: 'http://service.cn.maxcompute.aliyun.com/api', required: 1, encrypt: 2, tip: '' },
      { showName: '项目名称', key: 'project', value: 'my_project', required: 1, encrypt: 2, tip: '' },
      { showName: 'Access ID', key: 'accessId', value: 'LTAI******', required: 1, encrypt: 2, tip: '' },
      { showName: 'Access Key', key: 'accessKey', value: '******', required: 1, encrypt: 1, tip: '' },
    ],
  },
]

// 模拟 API 响应
export const mockResponse = <T>(data: T): ApiResponse<T> => ({
  code: 0,
  message: 'success',
  data,
})
