<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.data</groupId>
        <artifactId>profile-platform</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>profile-engine</artifactId>
    <packaging>pom</packaging>

    <name>profile-engine</name>

    <modules>
        <module>profile-engine-api</module>
        <module>profile-engine-plugins</module>
        <module>profile-engine-common</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.data</groupId>
            <artifactId>profile-common</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
