<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.data</groupId>
        <artifactId>profile-engine-analysis</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>profile-engine-clickhouse</artifactId>
    <name>profile-engine-clickhouse</name>

    <dependencies>
        <!-- 引擎API -->
        <dependency>
            <groupId>com.data</groupId>
            <artifactId>profile-engine-api</artifactId>
        </dependency>

        <!-- ClickHouse JDBC Driver -->
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.4.6</version>
            <classifier>http</classifier>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>
