server:
  port: 8080
#logging.config=classpath:logback.xml
management:
  server:
    port: 7016

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: prod
  application:
    name: profile-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/profile?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  clickhouse:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    url: jdbc:ch:http://localhost:8123/default
    username: test
    password: test
  authentication:
    providers:
      - passwd
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.data.profile.web.model
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.data.profile.web.handler
jwt:
  expireTime: 86400
  secretKey:
  algorithm: HS256

# 引擎全局配置参数
profile:
  engine:
    default-analysis-category: clickhouse
    default-di-category: DataX
    sync-channel: 3
    sync-error-record: 0
    sync-batch-size: 1000
    sync-write-mode: insert

# MinIO 配置
minio:
  # 默认端口号 9000 冲突改为 8000
  endpoint: http://localhost:8000
  access-key: EYA66D4zqFm6mWx9v15l
  secret-key: CwmmfKe4hzZsIXdUruwInIrvCVcat4UnWqYPJT1F
  bucket: profile