<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.data</groupId>
        <artifactId>profile-engine-plugins</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>profile-engine-all</artifactId>
    <name>profile-engine-all</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- 同步引擎 -->
        <dependency>
            <groupId>com.data</groupId>
            <artifactId>profile-engine-datax</artifactId>
            <version>1.0</version>
        </dependency>

        <dependency>
            <groupId>com.data</groupId>
            <artifactId>profile-engine-seatunnel</artifactId>
            <version>1.0</version>
        </dependency>

        <!-- 分析引擎 -->
        <dependency>
            <groupId>com.data</groupId>
            <artifactId>profile-engine-clickhouse</artifactId>
            <version>1.0</version>
        </dependency>

        <!-- 调度引擎 -->
        <dependency>
            <groupId>com.data</groupId>
            <artifactId>profile-engine-dolphinscheduler</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
</project>
